### ISSUE TITLE
畫面縮小時，左上小標誌顏色

### ISSUE THREAD

**Issue by c941010623** [AgoraIO/Basic-Audio-Call#13]
Hi Agora Team,

想請教一下，當我使用 Join channel 後，當我縮小 app
左上角的麥克風是紅色的，請問有背景錄音錄影嗎？？

我該如何讓它變成綠色的？？ (我查看了其他 APP 的通話都是綠色的)
因我的使用群都在懷疑我的 APP 有背景錄音錄影，
我該如何讓它變成綠色的呢？？

**Comment by plutoless** [comment]
您好，这个应该是系统的行为，绿色的icon代表系统电话通话，红色代表麦克风采集
详细的图标意义可以在这里看到 https://support.apple.com/zh-cn/HT207354
本质上我们并不是系统电话通话，所以显示红色icon是正常的。
