### ISSUE TITLE
teaching on youtub

### ISSUE THREAD

**Issue by 06050890** [AgoraIO/Basic-Audio-Call#21]
hope youtube   have agora voice group study    please

**Comment by sidsharma27** [comment]
Hi @06050890  what platform are you looking for?

**Comment by 06050890** [comment]
android studio   thank you

**Comment by sidsharma27** [comment]
Here you go: https://www.youtube.com/watch?v=gIuThUluO0U
The SDK version is outdated but the steps are all the same. Please don't hesitate to ask any questions in the integration process

**Comment by 06050890** [comment]
if i want use   "Group-Voice-Call"     
i download github agoraIO  code  ZIP   
open the android studio    ->open file    use   Group-voice-call   (android)
sign in agora    get app id ->     Paste  id in android studio   open the AVD ?

or   Restart creat new project ?

**Comment by 06050890** [comment]
https://drive.google.com/drive/folders/1M58VTX4VaJSWjjSL9oPFZ2baM0KMoPa2?usp=sharing

my step is  sure or wrong ???
