### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by 06050890** [AgoraIO/Basic-Audio-Call#23]
we open "open voice call"   
![image](https://user-images.githubusercontent.com/47807529/89736057-60f8f000-da99-11ea-9ae0-8cba60ca7385.png)

me and my friend channel name is "123"

join  
![image](https://user-images.githubusercontent.com/47807529/89736075-84bc3600-da99-11ea-9bfa-42c62182fb16.png)

we 're not sound to  chat  no sound   please help me   

android studio nexus 5x

**Comment by 06050890** [comment]
还有我可以打中文吗? 英文不太好

**Comment by plutoless** [comment]
可以的，您方便加个稍微特殊点的频道名吗？我后台查一下

**Comment by 06050890** [comment]
请问"加个稍微特殊点的频道名"是什么意思，不太懂意思，有想是不是android studio 不支援 麦克风

**Comment by yoreland** [comment]
android模拟器可能没有开启麦克风的.
尽量可以使用真机测试一下
