### ISSUE TITLE
Agora voice call stops audio after 1 minute of lock screen

### ISSUE THREAD

**Issue by shaifu** [AgoraIO/Basic-Audio-Call#28]
I have implemented agora voice call in my application. Its working fine on older devices and tabs but on new devices after locking the screen for 1 minute the receiver cannot hear audio.

**Comment by plutoless** [comment]
i think you will need to implement foreground service https://developer.android.com/guide/components/foreground-services to achieve this. the mic recording will stop after your app goes to background for certain period of time.

**Comment by shaifu** [comment]
Hi, 
Thanks for replying. I have solved the issue by foreground service. Thanks

**Comment by Brinfotech1407** [comment]
> Hi,
> Thanks for replying. I have solved the issue by foreground service. Thanks

Hello can you have any example for how to keep microphone and camera running in foreground service? thanks.

**Comment by chopper2201** [comment]
Hi @shaifu ,
Can you show me example to fix this issue on React Native Android?
