### ISSUE TITLE
can not resolve rtcEngine

### ISSUE THREAD

**Issue by Vishal-beep136** [AgoraIO/Basic-Audio-Call#32]
How to import rtcEngine can anyone help me.
I am getting error - cannot resolve symbol 'RtcEngine

**Comment by yoreland** [comment]
Hi, did you check below document?
https://docs.agora.io/en/Voice/start_call_audio_android?platform=Android

**Comment by Vishal-beep136** [comment]
> Hi, did you check below document?
> https://docs.agora.io/en/Voice/start_call_audio_android?platform=Android

thanks
