### ISSUE TITLE
[Voice SDK] playEffect not work playing specified audio files on Android Emulator in v2.8.1 and higher versions.

### ISSUE THREAD

**Issue by kkoudev** [AgoraIO/Basic-Audio-Call#4]
The IAudioEffectManager#playEffect method not work playing specified audio files on Android Emulator (Android 9) in Voice SDK v2.8.1, v2.8.2 and v2.9.0.
A default sound play instead.

But this method work playing specified audio files on Android Emulator (Android 9) in Voice SDK v2.8.0.

Please help it.

**Comment by brianxcli** [comment]
Can you give an example?  And are they of certain audio format, or files by link?

**Comment by kkoudev** [comment]
@brianxcli  I've create example project.
https://github.com/kkoudev/AgoraTest

Please set the App ID of Agora project in MainActivity.kt If you want to launch this project.
And the Agora version is set in app/build.gradle.

Please confirm it.

**Comment by yuhaonong** [comment]
Android simulator only supports mp3 format, AFAIK

**Comment by kkoudev** [comment]
@yuhaonong 
As with m4a format, mp3 files could not be played using the playEffect method on Android Emulator in v2.8.1 and higher versions.
But it have be able to play using the playEffect method on Android Emulator in v2.8.0.

I've added a mp3 file to this example project.
https://github.com/kkoudev/AgoraTest

Please confirm it.

**Comment by yuhaonong** [comment]
Sorry, forgot to mention that the mp3 file has to be in sdcard for emulator. and make sure you have grant the storage permission.

**Comment by kkoudev** [comment]
Ummm....
I want to know why audio files in assets directory can no longer be played on Android Emulator since Agora Voice SDK v2.8.1.
Because, it can be played on Android Emulator in Agora Voice SDK v2.8.0 and lower versions.
This issue is bug or specification change of Agora Voice SDK since Agora Voice SDK v2.8.1?
And do you know how to solve this problem?

**Comment by yuhaonong** [comment]
There was some issue in detecting emulator before v2.8.1 since some api was deprecated in Android-O onward. The requirement for audio files in SD card is probably because of some historical compatibility issue.
As a workaround for emulator, you can simply copy the asset file to sdcard.

**Comment by kkoudev** [comment]
@yuhaonong 
Thank you for your reply.
I've tried to play a mp3 file in the sdcard with playEffect method and it works fine.

Thanks!
